id: PEE9BD97E
initial_creation_type: ocr
source_metadata:
  volumes:
    eba1342e26ae49abaec9ffc031e754d7:
      base_file: v093.txt
      image_group_id: I1PD95938
      title: དགེ་ཚུལ་གྱི་དང་པོའི་ལོ།
      total_pages: 1484
      volume_number: 93
