id: D7D3A54B3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-12-31T06:51:37+00:00'
last_modified: '2022-05-30T04:06:27.590755+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    7ad1:
      image_group_id: I1PD95938
      title: དགེ་ཚུལ་གྱི་དང་པོའི་ལོ།
      total_pages: 1484
      order: 93
      base_file: 7ad1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
